# Generated by Django 5.1.4 on 2024-12-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='url',
            field=models.URLField(max_length=550, unique=True),
        ),
    ]
